Proiect in lucru
ITSchool-Web-Wizards/Proiect-HTML-CSS pull request #3
Opened 2024-03-11 11:07 UTC by k4pn0

![432208300_409949121713752_6483801680432731799_n](https://github.com/ITSchool-Web-Wizards/Proiect-HTML-CSS/assets/155654169/9a142c13-1c77-4d89-9075-39d58bb7bf97)
![431741247_2451384051728778_1637173491791003538_n](https://github.com/ITSchool-Web-Wizards/Proiect-HTML-CSS/assets/155654169/6629723b-dcd6-440b-bc62-fc67a924fb90)
Am intampinat mai multe probleme
      - Nu am reusit sa fac meniul hamburger pana la capat; am urmat un video pe youtube si la un moment dat ceva nu a mai mers
      - Am incercat sa fac latura de sus a div-ului cu silueta in main si footer. In main am incercat cu un png si acolo a murit iar in footer am folosit un svg, dar alinierea lui nu este corecta
      -pattern-ul din section (pe elementul asta voiam sa fac parallax si nu mi-a iesit inca) si imaginea care este in comment (m-am tot jucat cu position si overflow sa arate ca in design dar nu am reusit)
Nici celelalte doua pagini nu sunt intr-o stare prea buna.  Recunosc ca nu am ajuns in stadiul asta in incercarile mele de a invata front end si m-a coplesit un pic sau poate mi-am ales o tema complicata. Nu am stiut daca trebuie sa am mai multe fisiere css sau trebuia sa aranjez codul in unul singur.  Am subestimat timpul necesar temei alese si acum cred ca am lucrat haotic. Imi cer scuze. Daca ma poti ajuta cu feedback, trucuri, sfaturi etc iti multumesc anticipat. 
Atasat si designul pentru homepage

2024-03-11 14:03 UTC, vladutcornel commented
> am urmat un video pe youtube

Dă-mi link la video, te rog.

2024-03-11 14:16 UTC, k4pn0 commented
> > am urmat un video pe youtube
> 
> Dă-mi link la video, te rog.

https://youtu.be/dAIVbLrAb_U?si=3i26Wv0zQPPHVf55

2024-03-11 14:38 UTC, vladutcornel requested changes
Eu îți recomand să te concentrezi la chestiile pe care știi cum să le faci. Și ne uităm Marți la chestiile care îți dau bătăi de cap.

Mai bine faci mai puțin și bine.

2024-03-11 14:38 UTC, vladutcornel commented on index.html
> +        <a href="index.html"> <img src="/Proiect-HTML-CSS/images/milka-logo-purple.webp" alt="logo Milka" style="max-width: 30vw;"></a>
Mai bine pui adrese relative, care să nu conțină path-ul care apare în.

```suggestion
        <a href="index.html"> <img src="images/milka-logo-purple.webp" alt="logo Milka" style="max-width: 30vw;"></a>
```

2024-03-11 14:38 UTC, vladutcornel commented on index.html
> +            <input type="checkbox"/>
S-ar putea să te ajute dacă pui checkbox-ul înaintea meniului

```html
<input type="checkbox" class="menu-trigger"/>
<aside class="sliding-menu">
```

Asta te poate ajuta să faci un selector pentru atunci când checkbox-ul este bifat.

```css
input.menu-trigger:checked + .sliding-menu {
  /* Meniul este deschis */
}
```

2024-03-11 14:38 UTC, vladutcornel commented on index.html
> +    <h4>&#169 2024 Mondelez</h4>
Caracterele speciale trebuie să se termine cu `;`.

```suggestion
    <h4>&#169; 2024 Mondelez</h4>
```

Dar există caracter special mai sugestiv.
```suggestion
    <h4>&copy; 2024 Mondelez</h4>
```

2024-03-11 14:38 UTC, vladutcornel commented on style.css
> +        grid-template-columns: repeat (3, 1fr);
În CSS nu se pune spațiu înainte de `(`
```suggestion
        grid-template-columns: repeat(3, 1fr);
```

2024-03-11 14:38 UTC, vladutcornel commented on style.css
> +.hero-promo img {
Ai grijă că acest selector se potrivește și imaginilor pe care le ai în `.container-img`

2024-03-11 14:38 UTC, vladutcornel commented on style.css
> +@media screen and (min-width: 600px) {
Pe ecrane mai mari, ai conținutul mai lat decât ecranul. Pare să fie de la imaginile cu premii.

2024-03-11 14:38 UTC, vladutcornel commented on style.css
> +    max-width: 95vw;
Vezi dacă te ajută să pui și width
```suggestion
    max-width: 95vw;
    width: 100%;
```

2024-03-11 14:38 UTC, vladutcornel commented on index.html
> +    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="f4f4f7" fill-opacity="1" d="M0,256L60,218.7C120,181,240,107,360,74.7C480,43,600,53,720,85.3C840,117,960,171,1080,176C120
Cred că ai văzut că SVG-ul tău este invers. Poți să îi faci flip ori dintr-un editor, ori din CSS.

Oriunde i-ai face flip, eu aș zice că te-ar ajuta să îl pui altfel. Poate ca background la un element.

2024-03-11 15:04 UTC, k4pn0 commented
Mulțumesc mult pentru feedback și răbdare. O sa le fac și trimit din nou în seara asta. Cred că o să mă concentrez pe homepage sa fie totul bine și responsive și să nu mai fiu haotică. Posibil sa te asaltez cu alte întrebări și mâine.

2024-03-14 07:39 UTC, vladutcornel commented
Să nu uiți să îmi dai URL-ul de deploy.

2024-03-14 20:31 UTC, closed without merging